### ISSUE TITLE
Make UIScrollView in GINIOnboardingViewController public

### ISSUE THREAD

**Issue by subgit** [gini/gini-vision-lib-ios#19]
I need to set the contentOffset of the UIScrollView in my ContainerViewController. Can you make the UIScrollView property in GINIOnboardingViewController public readable?

**Comment by mpoprat** [comment]
Hi, and thanks for your remark. We will check this internally.

**Comment by mpoprat** [comment]
Hi, 

could you please provide us some more details about your use case for making UIScrollView public? Thanks!

Best

Gini Support Team

**Comment by mpoprat** [comment]
Hi,

a we didn't get any response on our last message, we will close this issue. Please feel free to re-open the issue if necessary. Thanks!

Best

Gini Support Team

**Comment by subgit** [comment]
Hi,
sorry I did not see your message. I need to adjust the content offset of the scrollview, for next or previous page. Also the contentOffset should be adjusted if one touches the pageControl.
