### ISSUE TITLE
Make GINICameraViewController cameraOverlay property public readable

### ISSUE THREAD

**Issue by subgit** [gini/gini-vision-lib-ios#22]
Hi,
I need to set a custom CameraOverlay image, can you make the camerOverlay UIImageView property public readable?
thx

**Comment by limfinity** [comment]
Thank you for your request! Do you just want to set your own custom image? As of today it is already possible to overwrite every image by setting it in your bundles asset catalogue. The Gini Vision Library will look for an asset preferred in your bundle before it will default to the image in it's own bundle. This has the advantage that on updating the Gini Vision Library the image will stay the same. Does this bring you sufficient flexibility?

This is from our [documentation](http://developer.gini.net/gini-vision-lib-ios/api/Classes/GINIConfiguration.html):
> Images can only be set by providing images with the same filename in an assets file or as individual files in the projects bundle. The library will prefer whatever value is set in the following order: asset file in project bundle, asset file in GiniVision bundle.

**Comment by subgit** [comment]
Unfortunately we do not have CocoaPods right now, so the GiniVisionSDK is added directly into the app target. If I use the documented way, there will be two images with the same name and one cannot reliably say which image will be used.

Also in my opinion it would be easier for the API user, to set an custom image manually. Right now the user must know the image name and "override" this image with his or her own image. Of course you have documented this, but I didn't see it.

Btw: My first approach was to use the GiniConfiguration class, as I have already with my custom strings. Why are you using for images an other way than for Strings?

But: We will soon integrate CocoaPods. Now I will delete the image from the SDK and when CocoaPods is integrated, it should use the correct image from the main bundle. So there is no need for you to do anything for us :) thank you

**Comment by limfinity** [comment]
That sounds great! 
Still I understand your problem and I'll keep the ticket around to track future process on this regard.

**Comment by nsobadjiev** [comment]
Available in versions:
2.0.2
3.0.2
2.3.2
