### ISSUE TITLE
Image capture in landscape mode

### ISSUE THREAD

**Issue by marcusficner** [gini/gini-vision-lib-ios#23]
Hi,
does the vision library support image capture in landscape mode?

**Comment by mpoprat** [comment]
Hi, 

thank you very much for your request. For sure you can take photos in landscape mode. Sometimes, you have to rotate the photo to get the correct reading direction. However, concerning the UI, the Gini Vision Library itself can't be used landscape mode.

Hope to help

Michael

**Comment by marcusficner** [comment]
All right, thank you!
