### ISSUE TITLE
Exposing members to Objective-C with Swift 4.2

### ISSUE THREAD

**Issue by lukas2** [gini/gini-vision-lib-ios#308]
I'm trying to instantiate Classes from this lib with Objective C, but the initialisers are not visible. For example in OnboardingViewController.swift, the @objc attribute is not sufficient. @objcMembers works. (Exposing the initialiser with @objc should work also.) Perhaps I am overlooking something, but I think this needs to happen in several other places as well.

References:
https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md
https://stackoverflow.com/a/47049571/340354

**Comment by kikettas** [comment]
What are the classes that you are trying to instantiate?

**Comment by lukas2** [comment]
Hi, my code wants AnalysisViewController, CameraViewController, OnboardingPage, OnboardingViewController, ReviewViewController. 

Here's the diff that makes my app build again: https://github.com/lukas2/gini-vision-lib-ios/commit/a5a14dd4cd48e7892a4eb9760eb24a0c6cf43d79

**Comment by kikettas** [comment]
Cool. I'm currently try it out and will give you an answer asap. 👍

**Comment by lukas2** [comment]
Great thank you!

**Comment by kikettas** [comment]
Fixed in latest release (4.3.2) 👍

**Comment by lukas2** [comment]
Thank you very much! 🙏 I'll use this asap.

**Comment by kikettas** [comment]
Let us know if you had any issue 👍
