### ISSUE TITLE
GiniVision Crash if resultsDelegate is deallocated 

### ISSUE THREAD

**Issue by vodaion** [gini/gini-vision-lib-ios#344]
Currently if resultDelegate object is deallocated the framework crash in GiniScreenAPICoordinator line 56.
For more details why it is happening please check this: https://stackoverflow.com/questions/16569840/using-objc-setassociatedobject-with-weak-references

**Comment by a-szotyori** [comment]
We released a fix in version [4.8.1](http://developer.gini.net/gini-vision-lib-ios/docs/changelog.html).
